#' plot each individual variable
#'
#' For every variable, creates plots using \code{\link{f_plot_CI_individuals}}.
#'
#' @param val
#' @param R_bootstrap
#' @param plot_format_list
#' @param output_fn_prefix
#'
#' @return NULL
#'
#' @examples
f_plot_CI_individuals_driver <-
function# plot each individual variable
###
(val
###
, R_bootstrap
###
, plot_format_list
###
, output_fn_prefix
###
)
{
  ##details<<
  ## For every variable, creates plots using \code{\link{f_plot_CI_individuals}}.

  f_plot_CI_individuals(val$bs$TDL$conc12CO2          , val$sum$TDL$conc12CO2          , val$CI$TDL$conc12CO2          , "val$sum$TDL$conc12CO2          ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$conc13CO2          , val$sum$TDL$conc13CO2          , val$CI$TDL$conc13CO2          , "val$sum$TDL$conc13CO2          ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$TGApressure        , val$sum$TDL$TGApressure        , val$CI$TDL$TGApressure        , "val$sum$TDL$TGApressure        ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$MassFlow1          , val$sum$TDL$MassFlow1          , val$CI$TDL$MassFlow1          , "val$sum$TDL$MassFlow1          ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$Pressure1          , val$sum$TDL$Pressure1          , val$CI$TDL$Pressure1          , "val$sum$TDL$Pressure1          ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$MassFlow2          , val$sum$TDL$MassFlow2          , val$CI$TDL$MassFlow2          , "val$sum$TDL$MassFlow2          ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$Pressure2          , val$sum$TDL$Pressure2          , val$CI$TDL$Pressure2          , "val$sum$TDL$Pressure2          ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$PressureProMan     , val$sum$TDL$PressureProMan     , val$CI$TDL$PressureProMan     , "val$sum$TDL$PressureProMan     ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$interp_tank_hi_12  , val$sum$TDL$interp_tank_hi_12  , val$CI$TDL$interp_tank_hi_12  , "val$sum$TDL$interp_tank_hi_12  ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$interp_tank_hi_13  , val$sum$TDL$interp_tank_hi_13  , val$CI$TDL$interp_tank_hi_13  , "val$sum$TDL$interp_tank_hi_13  ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$interp_tank_low_12 , val$sum$TDL$interp_tank_low_12 , val$CI$TDL$interp_tank_low_12 , "val$sum$TDL$interp_tank_low_12 ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$interp_tank_low_13 , val$sum$TDL$interp_tank_low_13 , val$CI$TDL$interp_tank_low_13 , "val$sum$TDL$interp_tank_low_13 ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$interp_reference_12, val$sum$TDL$interp_reference_12, val$CI$TDL$interp_reference_12, "val$sum$TDL$interp_reference_12", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$interp_reference_13, val$sum$TDL$interp_reference_13, val$CI$TDL$interp_reference_13, "val$sum$TDL$interp_reference_13", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$chamber_12         , val$sum$TDL$chamber_12         , val$CI$TDL$chamber_12         , "val$sum$TDL$chamber_12         ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$TDL$chamber_13         , val$sum$TDL$chamber_13         , val$CI$TDL$chamber_13         , "val$sum$TDL$chamber_13         ", 1:val$sum$TDL$n, val$sum$TDL$n, R_bootstrap, plot_format_list, output_fn_prefix)

  f_plot_CI_individuals(val$bs$Licor$FTime     , val$sum$Licor$FTime     , val$CI$Licor$FTime     , "val$sum$Licor$FTime     ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$A         , val$sum$Licor$A         , val$CI$Licor$A         , "val$sum$Licor$A         ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$gsc       , val$sum$Licor$gsc       , val$CI$Licor$gsc       , "val$sum$Licor$gsc       ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$Ci        , val$sum$Licor$Ci        , val$CI$Licor$Ci        , "val$sum$Licor$Ci        ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$E         , val$sum$Licor$E         , val$CI$Licor$E         , "val$sum$Licor$E         ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$VPD       , val$sum$Licor$VPD       , val$CI$Licor$VPD       , "val$sum$Licor$VPD       ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$La        , val$sum$Licor$La        , val$CI$Licor$La        , "val$sum$Licor$La        ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$StmRat    , val$sum$Licor$StmRat    , val$CI$Licor$StmRat    , "val$sum$Licor$StmRat    ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$gbw       , val$sum$Licor$gbw       , val$CI$Licor$gbw       , "val$sum$Licor$gbw       ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$temp_air  , val$sum$Licor$temp_air  , val$CI$Licor$temp_air  , "val$sum$Licor$temp_air  ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$temp_leaf , val$sum$Licor$temp_leaf , val$CI$Licor$temp_leaf , "val$sum$Licor$temp_leaf ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$temp_block, val$sum$Licor$temp_block, val$CI$Licor$temp_block, "val$sum$Licor$temp_block", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$Ce        , val$sum$Licor$Ce        , val$CI$Licor$Ce        , "val$sum$Licor$Ce        ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$Co        , val$sum$Licor$Co        , val$CI$Licor$Co        , "val$sum$Licor$Co        ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$xin       , val$sum$Licor$xin       , val$CI$Licor$xin       , "val$sum$Licor$xin       ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$xout      , val$sum$Licor$xout      , val$CI$Licor$xout      , "val$sum$Licor$xout      ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$rh_ref    , val$sum$Licor$rh_ref    , val$CI$Licor$rh_ref    , "val$sum$Licor$rh_ref    ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$rh_sam    , val$sum$Licor$rh_sam    , val$CI$Licor$rh_sam    , "val$sum$Licor$rh_sam    ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$uin       , val$sum$Licor$uin       , val$CI$Licor$uin       , "val$sum$Licor$uin       ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$par_int   , val$sum$Licor$par_int   , val$CI$Licor$par_int   , "val$sum$Licor$par_int   ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$par_ext   , val$sum$Licor$par_ext   , val$CI$Licor$par_ext   , "val$sum$Licor$par_ext   ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$Atm_press , val$sum$Licor$Atm_press , val$CI$Licor$Atm_press , "val$sum$Licor$Atm_press ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$CsMch     , val$sum$Licor$CsMch     , val$CI$Licor$CsMch     , "val$sum$Licor$CsMch     ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$HsMch     , val$sum$Licor$HsMch     , val$CI$Licor$HsMch     , "val$sum$Licor$HsMch     ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$StableF   , val$sum$Licor$StableF   , val$CI$Licor$StableF   , "val$sum$Licor$StableF   ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$Status    , val$sum$Licor$Status    , val$CI$Licor$Status    , "val$sum$Licor$Status    ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$VpdA      , val$sum$Licor$VpdA      , val$CI$Licor$VpdA      , "val$sum$Licor$VpdA      ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$Ci_Ca     , val$sum$Licor$Ci_Ca     , val$CI$Licor$Ci_Ca     , "val$sum$Licor$Ci_Ca     ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$pi        , val$sum$Licor$pi        , val$CI$Licor$pi        , "val$sum$Licor$pi        ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$uc_20_mV  , val$sum$Licor$uc_20_mV  , val$CI$Licor$uc_20_mV  , "val$sum$Licor$uc_20_mV  ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$uc_21_mV  , val$sum$Licor$uc_21_mV  , val$CI$Licor$uc_21_mV  , "val$sum$Licor$uc_21_mV  ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$U_S       , val$sum$Licor$U_S       , val$CI$Licor$U_S       , "val$sum$Licor$U_S       ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$Trans     , val$sum$Licor$Trans     , val$CI$Licor$Trans     , "val$sum$Licor$Trans     ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$CndCO2    , val$sum$Licor$CndCO2    , val$CI$Licor$CndCO2    , "val$sum$Licor$CndCO2    ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$Ref_mV    , val$sum$Licor$Ref_mV    , val$CI$Licor$Ref_mV    , "val$sum$Licor$Ref_mV    ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$xTemp1    , val$sum$Licor$xTemp1    , val$CI$Licor$xTemp1    , "val$sum$Licor$xTemp1    ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$bs$Licor$xTemp2    , val$sum$Licor$xTemp2    , val$CI$Licor$xTemp2    , "val$sum$Licor$xTemp2    ", 1:val$sum$Licor$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)

  f_plot_CI_individuals(val$calc$bs$gain_12C                                              , val$calc$sum$gain_12C                                              , val$calc$CI$gain_12C                                              , "val$calc$sum$gain_12C                                              ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$gain_13C                                              , val$calc$sum$gain_13C                                              , val$calc$CI$gain_13C                                              , "val$calc$sum$gain_13C                                              ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$offset_12C                                            , val$calc$sum$offset_12C                                            , val$calc$CI$offset_12C                                            , "val$calc$sum$offset_12C                                            ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$offset_13C                                            , val$calc$sum$offset_13C                                            , val$calc$CI$offset_13C                                            , "val$calc$sum$offset_13C                                            ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$reference_12Ce                                        , val$calc$sum$reference_12Ce                                        , val$calc$CI$reference_12Ce                                        , "val$calc$sum$reference_12Ce                                        ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$reference_13Ce                                        , val$calc$sum$reference_13Ce                                        , val$calc$CI$reference_13Ce                                        , "val$calc$sum$reference_13Ce                                        ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12Co                                          , val$calc$sum$chamber_12Co                                          , val$calc$CI$chamber_12Co                                          , "val$calc$sum$chamber_12Co                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13Co                                          , val$calc$sum$chamber_13Co                                          , val$calc$CI$chamber_13Co                                          , "val$calc$sum$chamber_13Co                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$reference_TotalCe                                     , val$calc$sum$reference_TotalCe                                     , val$calc$CI$reference_TotalCe                                     , "val$calc$sum$reference_TotalCe                                     ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_TotalCo                                       , val$calc$sum$chamber_TotalCo                                       , val$calc$CI$chamber_TotalCo                                       , "val$calc$sum$chamber_TotalCo                                       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_reference_Total_diff_CeCo                     , val$calc$sum$chamber_reference_Total_diff_CeCo                     , val$calc$CI$chamber_reference_Total_diff_CeCo                     , "val$calc$sum$chamber_reference_Total_diff_CeCo                     ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_reference_12_diff_CeCo                        , val$calc$sum$chamber_reference_12_diff_CeCo                        , val$calc$CI$chamber_reference_12_diff_CeCo                        , "val$calc$sum$chamber_reference_12_diff_CeCo                        ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_reference_13_diff_CeCo                        , val$calc$sum$chamber_reference_13_diff_CeCo                        , val$calc$CI$chamber_reference_13_diff_CeCo                        , "val$calc$sum$chamber_reference_13_diff_CeCo                        ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$xi                                                    , val$calc$sum$xi                                                    , val$calc$CI$xi                                                    , "val$calc$sum$xi                                                    ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  # f_plot_CI_individuals(val$calc$bs$flow_adjusted                                         , val$calc$sum$flow_adjusted                                         , val$calc$CI$flow_adjusted                                         , "val$calc$sum$flow_adjusted                                         ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix) #  9/5/2012
  f_plot_CI_individuals(val$calc$bs$TDL_A_photosynthesis                                  , val$calc$sum$TDL_A_photosynthesis                                  , val$calc$CI$TDL_A_photosynthesis                                  , "val$calc$sum$TDL_A_photosynthesis                                  ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$TDL_12A_photosynthesis                                , val$calc$sum$TDL_12A_photosynthesis                                , val$calc$CI$TDL_12A_photosynthesis                                , "val$calc$sum$TDL_12A_photosynthesis                                ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$TDL_13A_photosynthesis                                , val$calc$sum$TDL_13A_photosynthesis                                , val$calc$CI$TDL_13A_photosynthesis                                , "val$calc$sum$TDL_13A_photosynthesis                                ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$Licor_A_photosynthesis                                , val$calc$sum$Licor_A_photosynthesis                                , val$calc$CI$Licor_A_photosynthesis                                , "val$calc$sum$Licor_A_photosynthesis                                ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$Delta_from_ratios_in_out                              , val$calc$sum$Delta_from_ratios_in_out                              , val$calc$CI$Delta_from_ratios_in_out                              , "val$calc$sum$Delta_from_ratios_in_out                              ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$Delta_from_A_ratio                                    , val$calc$sum$Delta_from_A_ratio                                    , val$calc$CI$Delta_from_A_ratio                                    , "val$calc$sum$Delta_from_A_ratio                                    ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$VPD                                                   , val$calc$sum$VPD                                                   , val$calc$CI$VPD                                                   , "val$calc$sum$VPD                                                   ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$E_transpiration                                       , val$calc$sum$E_transpiration                                       , val$calc$CI$E_transpiration                                       , "val$calc$sum$E_transpiration                                       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$leaf_temp                                             , val$calc$sum$leaf_temp                                             , val$calc$CI$leaf_temp                                             , "val$calc$sum$leaf_temp                                             ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$air_temp                                              , val$calc$sum$air_temp                                              , val$calc$CI$air_temp                                              , "val$calc$sum$air_temp                                              ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$light_in                                              , val$calc$sum$light_in                                              , val$calc$CI$light_in                                              , "val$calc$sum$light_in                                              ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$light_out                                             , val$calc$sum$light_out                                             , val$calc$CI$light_out                                             , "val$calc$sum$light_out                                             ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$reference_delta_e                                     , val$calc$sum$reference_delta_e                                     , val$calc$CI$reference_delta_e                                     , "val$calc$sum$reference_delta_e                                     ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_delta_o                                       , val$calc$sum$chamber_delta_o                                       , val$calc$CI$chamber_delta_o                                       , "val$calc$sum$chamber_delta_o                                       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_reference_delta_diff_CoCe                     , val$calc$sum$chamber_reference_delta_diff_CoCe                     , val$calc$CI$chamber_reference_delta_diff_CoCe                     , "val$calc$sum$chamber_reference_delta_diff_CoCe                     ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$Delta_obs                                             , val$calc$sum$Delta_obs                                             , val$calc$CI$Delta_obs                                             , "val$calc$sum$Delta_obs                                             ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$Delta_obs_permil                                      , val$calc$sum$Delta_obs_permil                                      , val$calc$CI$Delta_obs_permil                                      , "val$calc$sum$Delta_obs_permil                                      ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$delta_13C_Assim                                       , val$calc$sum$delta_13C_Assim                                       , val$calc$CI$delta_13C_Assim                                       , "val$calc$sum$delta_13C_Assim                                       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$p                                                     , val$calc$sum$p                                                     , val$calc$CI$p                                                     , "val$calc$sum$p                                                     ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$delta_13C_Resp                                        , val$calc$sum$delta_13C_Resp                                        , val$calc$CI$delta_13C_Resp                                        , "val$calc$sum$delta_13C_Resp                                        ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_TotalCa                                       , val$calc$sum$chamber_TotalCa                                       , val$calc$CI$chamber_TotalCa                                       , "val$calc$sum$chamber_TotalCa                                       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12Ca                                          , val$calc$sum$chamber_12Ca                                          , val$calc$CI$chamber_12Ca                                          , "val$calc$sum$chamber_12Ca                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13Ca                                          , val$calc$sum$chamber_13Ca                                          , val$calc$CI$chamber_13Ca                                          , "val$calc$sum$chamber_13Ca                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_TotalCs                                       , val$calc$sum$chamber_TotalCs                                       , val$calc$CI$chamber_TotalCs                                       , "val$calc$sum$chamber_TotalCs                                       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12Cs                                          , val$calc$sum$chamber_12Cs                                          , val$calc$CI$chamber_12Cs                                          , "val$calc$sum$chamber_12Cs                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13Cs                                          , val$calc$sum$chamber_13Cs                                          , val$calc$CI$chamber_13Cs                                          , "val$calc$sum$chamber_13Cs                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalpa                                       , val$calc$sum$chamber_Totalpa                                       , val$calc$CI$chamber_Totalpa                                       , "val$calc$sum$chamber_Totalpa                                       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12pa                                          , val$calc$sum$chamber_12pa                                          , val$calc$CI$chamber_12pa                                          , "val$calc$sum$chamber_12pa                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13pa                                          , val$calc$sum$chamber_13pa                                          , val$calc$CI$chamber_13pa                                          , "val$calc$sum$chamber_13pa                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalps                                       , val$calc$sum$chamber_Totalps                                       , val$calc$CI$chamber_Totalps                                       , "val$calc$sum$chamber_Totalps                                       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12ps                                          , val$calc$sum$chamber_12ps                                          , val$calc$CI$chamber_12ps                                          , "val$calc$sum$chamber_12ps                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13ps                                          , val$calc$sum$chamber_13ps                                          , val$calc$CI$chamber_13ps                                          , "val$calc$sum$chamber_13ps                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalgbw                                      , val$calc$sum$chamber_Totalgbw                                      , val$calc$CI$chamber_Totalgbw                                      , "val$calc$sum$chamber_Totalgbw                                      ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalgbc                                      , val$calc$sum$chamber_Totalgbc                                      , val$calc$CI$chamber_Totalgbc                                      , "val$calc$sum$chamber_Totalgbc                                      ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12gbc                                         , val$calc$sum$chamber_12gbc                                         , val$calc$CI$chamber_12gbc                                         , "val$calc$sum$chamber_12gbc                                         ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13gbc                                         , val$calc$sum$chamber_13gbc                                         , val$calc$CI$chamber_13gbc                                         , "val$calc$sum$chamber_13gbc                                         ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalgsw                                      , val$calc$sum$chamber_Totalgsw                                      , val$calc$CI$chamber_Totalgsw                                      , "val$calc$sum$chamber_Totalgsw                                      ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalgsc                                      , val$calc$sum$chamber_Totalgsc                                      , val$calc$CI$chamber_Totalgsc                                      , "val$calc$sum$chamber_Totalgsc                                      ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12gsc                                         , val$calc$sum$chamber_12gsc                                         , val$calc$CI$chamber_12gsc                                         , "val$calc$sum$chamber_12gsc                                         ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13gsc                                         , val$calc$sum$chamber_13gsc                                         , val$calc$CI$chamber_13gsc                                         , "val$calc$sum$chamber_13gsc                                         ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalgtc                                      , val$calc$sum$chamber_Totalgtc                                      , val$calc$CI$chamber_Totalgtc                                      , "val$calc$sum$chamber_Totalgtc                                      ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12gtc                                         , val$calc$sum$chamber_12gtc                                         , val$calc$CI$chamber_12gtc                                         , "val$calc$sum$chamber_12gtc                                         ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13gtc                                         , val$calc$sum$chamber_13gtc                                         , val$calc$CI$chamber_13gtc                                         , "val$calc$sum$chamber_13gtc                                         ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_TotalCi                                       , val$calc$sum$chamber_TotalCi                                       , val$calc$CI$chamber_TotalCi                                       , "val$calc$sum$chamber_TotalCi                                       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12Ci                                          , val$calc$sum$chamber_12Ci                                          , val$calc$CI$chamber_12Ci                                          , "val$calc$sum$chamber_12Ci                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13Ci                                          , val$calc$sum$chamber_13Ci                                          , val$calc$CI$chamber_13Ci                                          , "val$calc$sum$chamber_13Ci                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalpi                                       , val$calc$sum$chamber_Totalpi                                       , val$calc$CI$chamber_Totalpi                                       , "val$calc$sum$chamber_Totalpi                                       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12pi                                          , val$calc$sum$chamber_12pi                                          , val$calc$CI$chamber_12pi                                          , "val$calc$sum$chamber_12pi                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13pi                                          , val$calc$sum$chamber_13pi                                          , val$calc$CI$chamber_13pi                                          , "val$calc$sum$chamber_13pi                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalpi_pa                                    , val$calc$sum$chamber_Totalpi_pa                                    , val$calc$CI$chamber_Totalpi_pa                                    , "val$calc$sum$chamber_Totalpi_pa                                    ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Delta_i_simple_for_gm                         , val$calc$sum$chamber_Delta_i_simple_for_gm                         , val$calc$CI$chamber_Delta_i_simple_for_gm                         , "val$calc$sum$chamber_Delta_i_simple_for_gm                         ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Delta_i_simple_for_modeling                   , val$calc$sum$chamber_Delta_i_simple_for_modeling                   , val$calc$CI$chamber_Delta_i_simple_for_modeling                   , "val$calc$sum$chamber_Delta_i_simple_for_modeling                   ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Delta_i_complex_for_gm                        , val$calc$sum$chamber_Delta_i_complex_for_gm                        , val$calc$CI$chamber_Delta_i_complex_for_gm                        , "val$calc$sum$chamber_Delta_i_complex_for_gm                        ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Delta_i_simple_for_gm_Delta_obs               , val$calc$sum$chamber_Delta_i_simple_for_gm_Delta_obs               , val$calc$CI$chamber_Delta_i_simple_for_gm_Delta_obs               , "val$calc$sum$chamber_Delta_i_simple_for_gm_Delta_obs               ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Delta_i_complex_for_gm_Delta_obs              , val$calc$sum$chamber_Delta_i_complex_for_gm_Delta_obs              , val$calc$CI$chamber_Delta_i_complex_for_gm_Delta_obs              , "val$calc$sum$chamber_Delta_i_complex_for_gm_Delta_obs              ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalgm_point_simple                          , val$calc$sum$chamber_Totalgm_point_simple                          , val$calc$CI$chamber_Totalgm_point_simple                          , "val$calc$sum$chamber_Totalgm_point_simple                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12gm_point_simple                             , val$calc$sum$chamber_12gm_point_simple                             , val$calc$CI$chamber_12gm_point_simple                             , "val$calc$sum$chamber_12gm_point_simple                             ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13gm_point_simple                             , val$calc$sum$chamber_13gm_point_simple                             , val$calc$CI$chamber_13gm_point_simple                             , "val$calc$sum$chamber_13gm_point_simple                             ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalgm_point_complex                         , val$calc$sum$chamber_Totalgm_point_complex                         , val$calc$CI$chamber_Totalgm_point_complex                         , "val$calc$sum$chamber_Totalgm_point_complex                         ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalgm_to_use                                , val$calc$sum$chamber_Totalgm_to_use                                , val$calc$CI$chamber_Totalgm_to_use                                , "val$calc$sum$chamber_Totalgm_to_use                                ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalpc_using_gm                              , val$calc$sum$chamber_Totalpc_using_gm                              , val$calc$CI$chamber_Totalpc_using_gm                              , "val$calc$sum$chamber_Totalpc_using_gm                              ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12pc_using_gm                                 , val$calc$sum$chamber_12pc_using_gm                                 , val$calc$CI$chamber_12pc_using_gm                                 , "val$calc$sum$chamber_12pc_using_gm                                 ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13pc_using_gm                                 , val$calc$sum$chamber_13pc_using_gm                                 , val$calc$CI$chamber_13pc_using_gm                                 , "val$calc$sum$chamber_13pc_using_gm                                 ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalpc_using_simple_Delta_for_gm             , val$calc$sum$chamber_Totalpc_using_simple_Delta_for_gm             , val$calc$CI$chamber_Totalpc_using_simple_Delta_for_gm             , "val$calc$sum$chamber_Totalpc_using_simple_Delta_for_gm             ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalpc_using_simple_Delta_for_modeling       , val$calc$sum$chamber_Totalpc_using_simple_Delta_for_modeling       , val$calc$CI$chamber_Totalpc_using_simple_Delta_for_modeling       , "val$calc$sum$chamber_Totalpc_using_simple_Delta_for_modeling       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalpc_using_complex_Delta_no_decarboxylation, val$calc$sum$chamber_Totalpc_using_complex_Delta_no_decarboxylation, val$calc$CI$chamber_Totalpc_using_complex_Delta_no_decarboxylation, "val$calc$sum$chamber_Totalpc_using_complex_Delta_no_decarboxylation", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalpc_using_complex_Delta_full_model        , val$calc$sum$chamber_Totalpc_using_complex_Delta_full_model        , val$calc$CI$chamber_Totalpc_using_complex_Delta_full_model        , "val$calc$sum$chamber_Totalpc_using_complex_Delta_full_model        ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_Totalpc_to_use                                , val$calc$sum$chamber_Totalpc_to_use                                , val$calc$CI$chamber_Totalpc_to_use                                , "val$calc$sum$chamber_Totalpc_to_use                                ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_TotalCc                                       , val$calc$sum$chamber_TotalCc                                       , val$calc$CI$chamber_TotalCc                                       , "val$calc$sum$chamber_TotalCc                                       ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_12Cc                                          , val$calc$sum$chamber_12Cc                                          , val$calc$CI$chamber_12Cc                                          , "val$calc$sum$chamber_12Cc                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)
  f_plot_CI_individuals(val$calc$bs$chamber_13Cc                                          , val$calc$sum$chamber_13Cc                                          , val$calc$CI$chamber_13Cc                                          , "val$calc$sum$chamber_13Cc                                          ", 1:val$sum$TDL$n, val$sum$Licor$n, R_bootstrap, plot_format_list, output_fn_prefix)

  invisible(NULL);
  ### NULL
}

